spring:
  jpa:
    show-sql: true
    database: Oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
security:
  oauth2:
    resource:
      userInfoUri: https://test-lmidp.libertymutual.com/idp/userinfo.openid
  config:
    service-id: ci_lmbc_empr_muw_ui
    service-password: ENC(19C13FB2320AE15D4274E6604C32BF96)
    user-search-base: uid={0},ou=People,o=Liberty,o=Intranet
    ssid-search-base: uid={0},ou=People,o=Applications,o=Intranet
    group-search-base: cn=Products,ou=Groups,o=Liberty,o=intranet
    ldap-url: ldaps://ldapsintdev-01.lmig.com:636
    employee-read-access-groups: 
      - CI_LMBC_EMPR_MUW_QA
      - CI_LMBC_EMPR_MUW_SALES
      - CI_LMBC_EMPR_MUW_REPORTING
      - CI_LMBC_EMPR_MUW_CLAIMS
      - CI_LMBC_EMPR_MUW_CALLCENTER
      - CI_LMBC_EMPR_MUW_IT
      - CI_LMBC_EMPR_MUW_TECHNICIAN
      - CI_LMBC_EMPR_MUW_UNDERWRITER
      - CI_LMBC_EMPR_MUW_MANAGER
      - CI_LMBC_EMPR_MUW_DIRECTOR
      - CI_LMBC_EMPR_MUW_FILEFEED
      - CI_LMBC_EMPR_MUW_EMP
      - CI_LMBC_EMPR_MUW_ACCT
      - CI_LMBC_EMPR_MUW_TEST
    employee-create-access-groups: 
      - CI_LMBC_EMPR_MUW_IT
      - CI_LMBC_EMPR_MUW_TECHNICIAN
      - CI_LMBC_EMPR_MUW_UNDERWRITER
      - CI_LMBC_EMPR_MUW_MANAGER
      - CI_LMBC_EMPR_MUW_DIRECTOR
      - CI_LMBC_EMPR_MUW_EMP
      - CI_LMBC_EMPR_MUW_ACCT
      - CI_LMBC_EMPR_MUW_TEST
    employee-update-access-groups:  
      - CI_LMBC_EMPR_MUW_QA
      - CI_LMBC_EMPR_MUW_REPORTING
      - CI_LMBC_EMPR_MUW_CLAIMS
      - CI_LMBC_EMPR_MUW_CALLCENTER
      - CI_LMBC_EMPR_MUW_IT
      - CI_LMBC_EMPR_MUW_TECHNICIAN
      - CI_LMBC_EMPR_MUW_UNDERWRITER
      - CI_LMBC_EMPR_MUW_MANAGER
      - CI_LMBC_EMPR_MUW_DIRECTOR
      - CI_LMBC_EMPR_MUW_FILEFEED   
      - CI_LMBC_EMPR_MUW_EMP
      - CI_LMBC_EMPR_MUW_ACCT
      - CI_LMBC_EMPR_MUW_TEST
    employee-event-access-groups: 
      - CI_LMBC_EMPR_MUW_EMPLOYEE_EVT
      - CI_LMBC_EMPR_MUW_TEST
      - CI_LMBC_EMPR_DEVELOPER
logging:
  level: 
    ROOT: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type: DEBUG   

datasource:
  app:
    url: jdbc:oracle:thin:@vxpid-c5lb0011.lmig.com:1528:clb0p11d
    username: MUWEMPSVCAP
    password: ENC(6B27790F9CD03E180645493E1DD5E380)
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    url: jdbc:oracle:thin:@vxpid-c5lb0011.lmig.com:1528:clb0p11d
    username: MUWEMP_DB
    password: ENC(B7B53CDD8B8656439FB95AE97B1B1290)
    driver-class-name: oracle.jdbc.OracleDriver
flyway:
  locations: classpath:db/migration/versioned,db/migration/repeatable
  placeholders:
    BIGSTRING: VARCHAR2
    NUMBER8: NUMBER(8)
    DATETIME: TIMESTAMP
    NUMBER11_2: NUMBER(11,2)
    NUMBER5: NUMBER(5)
    NUMBER10: NUMBER(10)
    SETSCHEMA: ALTER SESSION SET CURRENT_SCHEMA =
    IDENTITY_EMPLR_EMP_1_1: 
    IDENTITY_EMPLR_EMP_EVENT_1_1:
    NUMBER19: NUMBER(19)
    EMPLOYEE_PK: ALTER TABLE emplr_emp_t ADD CONSTRAINT pk_muw_emplr_emp_t PRIMARY KEY(emplr_emp_id);
    EMPLR_EMP_EVENT_PK: ALTER TABLE emplr_emp_event_t ADD CONSTRAINT pk_emplr_emp_event_t PRIMARY KEY(event_id);
    H2IGNORELINE:
    iforacle: 
    ifjunit: -- 

service:
  employerServiceUrl: https://dev1-lmbc-empr-muw-account-service.pdc.np.paas.lmig.com/services/v1/
  employerServiceId: ci_lmbc_empr_muw_ui
  employerServicePassword: ENC(19C13FB2320AE15D4274E6604C32BF96)   
  contactServiceUrl: https://dev1-lmbc-empr-contact-service.pdc.np.paas.lmig.com/services/v1/
    
    