spring:
  jpa:
    show-sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

logging:
  level: 
    ROOT: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    org.hibernate.type: INFO
    
security:
  oauth2:
    resource:
      userInfoUri: https://test-lmidp.libertymutual.com/idp/userinfo.openid
  config:
    read-access-groups:
      - USER
      - ADMIN
    read-write-access-groups:
      - ADMIN
    read-access-event-groups:
      - ADMIN
h2:
  tcp:
    enabled: true
  web:
    enabled: true    

datasource:
  app:
    url: jdbc:h2:mem:account_lcl;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:db/h2/init/h2_setup.sql'
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    url: jdbc:h2:mem:account_lcl;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:db/h2/init/h2_setup.sql'
    username: sa
    password:
    driver-class-name: org.h2.Driver

flyway:
  locations: classpath:db/migration/versioned,db/migration/repeatable,db/h2/post_create
  placeholders:
    BIGSTRING: VARCHAR2
    DATETIME: TIMESTAMP
    NUMBER11_2: NUMBER(11,2)
    NUMBER5: NUMBER(5)
    NUMBER10: NUMBER(10)
    SETSCHEMA: SET SCHEMA
    IDENTITY_1_1: AUTO_INCREMENT
    IDENTITY_EMPLR_1_1: DEFAULT MUW_EMPLR_SEQ.NEXTVAL PRIMARY KEY
    IDENTITY_PREF_1_1: DEFAULT MUW_PREF_SEQ.NEXTVAL PRIMARY KEY
    IDENTITY_EOIPROD_1_1: DEFAULT MUW_EOIPROD_SEQ.NEXTVAL PRIMARY KEY
    IDENTITY_EMPLR_EVNT_1_1: DEFAULT MUW_EMPLR_EVNT_SEQ.NEXTVAL PRIMARY KEY
    NUMBER19: BIGINT
    EMPLOYER_PK:
    LABEL_TXT_PK: ALTER TABLE lbl_txt_t ADD CONSTRAINT pk_lbl_txt_t PRIMARY KEY(lbl_id);
    PROD_LBL_PK: ALTER TABLE prod_lbl_t ADD CONSTRAINT pk_prod_lbl_t PRIMARY KEY(prod_id, lbl_id);
    PREF_LBL_PK: ALTER TABLE pref_lbl_t ADD CONSTRAINT pk_pref_lbl_t PRIMARY KEY(emplr_prefcs_id, pref_type, lbl_id);
    EMPLOYER_EVENT_PK:
    iforacle: --
    ifjunit: 
    H2IGNORELINE: --
    ORACLEIGNORELINE:
    