/* SET SCHEMA FOR SESSION */
${SETSCHEMA} MUWACCT_DB;

ALTER TABLE MUWACCT_DB.EMPLR_EOI_PROD_T ADD CCRCY_QTY ${NUMBER5} NULL;
UPDATE MUWACCT_DB.EMPLR_EOI_PROD_T SET CCRCY_QTY=0;
ALTER TABLE MUWACCT_DB.EMPLR_EOI_PROD_T MODIFY CCRCY_QTY ${NUMBER5} not null;

ALTER TABLE MUWACCT_DB.MUW_EMPLR_EVNT_T ADD CCRCY_QTY ${NUMBER5} NULL; 
UPDATE MUWACCT_DB.MUW_EMPLR_EVNT_T SET CCRCY_QTY=0;
ALTER TABLE MUWACCT_DB.MUW_EMPLR_EVNT_T MODIFY CCRCY_QTY ${NUMBER5} not null;